name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 2.1.0
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bitmovin_player:
    path: /Users/nicolas/dev/bitmovin_player
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_widget_from_html_core: ^0.9.1
  http: ^0.13.4
  http_parser: ^4.0.1
  video_player: ^2.4.2
  google_fonts: ^4.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true